baseURL = "https://blog.brokenkernel.com"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = "pop %eax"
theme = [ "hugo-notice", "roadster" ]

enableInlineShortcodes = true
enableGitInfo = true
enableMissingTranslationPlaceholders = true

[languages]
  [languages.en]
    languageName = 'English'
    languageCode = "en-US"

[Params]
  subtitle = "32 bits of writing"
  description = "testing things"
  authorbox = false
  toc = false
  pager = true
  mathjax = true
  readmore = true
  mathjaxConfig = "TeX-MML-AM_CHTML"
  # mathjaxPath = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  post_meta = ["author", "date", "categories", "translations"]
  opengraph = true
  customCSS = ["css/custom.css"]


[Params.footer]
  widgets = ["comments"]

[Params.sidebar]
  home = "left"
  list = "left"
  single = "left"
  widgets = ["search", "recent", "categories", "sidemenu", "taglist", "languages", "comments"]

[Params.author]
  name = "Eitan Adler"
  bio = "human. occasionally helpful."

[Paginator]
  pagerSize = 10

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[build]
writeStats = true
