baseURL = "https://blog.brokenkernel.com"
languageCode = "en-us"
title = "pop %eax"
theme = "mainroad"

enableInlineShortcodes = true
enableGitInfo = true

paginate = "10"

[Author]
  name = "Eitan Adler"
  bio = "32 bits of writing"

[Params]
  subtitle = "quickly written content"
  description = "testing things"
  authorbox = false
  toc = false
  pager = true
  mathjax = true
  mathjaxPath = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

[Params.footer]
  widgets = ["comments"]

[Params.sidebar]
  home = "left"
  list = "left"
  single = "left"
  widgets = ["search", "recent", "categories", "sidemenu", "taglist", "languages", "comments"]


[build]
writeStats = true
