baseURL = "https://blog.brokenkernel.com"
languageCode = "en-US"
title = "pop %eax"
theme = "mainroad"

enableInlineShortcodes = true
enableGitInfo = true
enableMissingTranslationPlaceholders = true

paginate = "10"

[Author]
  name = "Eitan Adler"
  bio = "human. occasionally helpful."

[Params]
  subtitle = "32 bits of writing"
  description = "testing things"
  authorbox = false
  toc = false
  pager = true
  mathjax = true
  readmore = true
  mathjaxConfig = "TeX-MML-AM_CHTML"
  # mathjaxPath = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

  opengraph = true


[Params.footer]
  widgets = ["comments"]

[Params.sidebar]
  home = "left"
  list = "left"
  single = "left"
  widgets = ["search", "recent", "categories", "sidemenu", "taglist", "languages", "comments"]


[build]
writeStats = true
